version: "3.8"

services:
  mssql:
    build: ./setup/database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1Secure*Password1"
      MSSQL_SA_PASSWORD: "1Secure*Password1"
    volumes:
      - myinr-db:/var/opt/mssql
    networks:
      - myinr-main-network
    ports:
      - 1436:1433
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 4000M
        reservations:
          cpus: 0.25
          memory: 3500M
volumes:
  myinr-db:

networks:
  myinr-main-network: